Code Review
Nanostring-Biostats/SpatialOmicsOverlay pull request #2
Opened 2022-04-11 17:25 UTC by maddygriz

2022-04-12 19:57 UTC, NicoleEO requested changes
xmlParsing.R comments

- [x] throughout code roxygen tag @importFrom, package name should be before function names
- [x] Change "some AOIs do no" --> "some AOIs do not"
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/174cfe7ddba836e40d987a7a1d7cfe434ab6b00a/R/xmlParsing.R#L143
- [x] Do you even need the column rename? Also, is the warning saying the opposite of what's going on? There are more annotations then AOIs. So some AOIs in annotation file not in experiment?
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/174cfe7ddba836e40d987a7a1d7cfe434ab6b00a/R/xmlParsing.R#L142

Column rename allows GxT object to go through same logic as the lab worksheet. This package only works on 1 slide at a time but someone could give an entire study (multiple slides) worth of annotations. 

- [x] Title case is usually reserved for classes (PhysicalSizeX and Y, Fluorescence)
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/xmlParsing.R#L168
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/xmlParsing.R#L207
- [x] Put globals at the top of the file
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/xmlParsing.R#L180
- [x] Didn't chan just get 1 added in Line 232? The line quoted below also has a +1 so you are skipping a line for the ==ChannelInfo check. Maybe this should just be rewritten to for loop?
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/xmlParsing.R#L244
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/xmlParsing.R#L255

I agree this is not the best written code but I don't think a for loop will work. The XML files have varying lines for the fluorescence data and this was actually the easiest way I could figure out how to accurately get the data. I will look into condensing this code if I have time before the release but it's probably at the bottom of my list. 

@maddygriz just to confirm so that's correct you add one (L232) then and another (L244/L255) before using to do check for Channel Info? So 2 indices away from starting point.
@NicoleEO yes the add on L232 gets to the correct line and then lines L244/255 looks at the next line to see what the next line looks like to affect the logic. 

- [x] What software is being referenced here?
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/xmlParsing.R#L326

No software, literally the number of masks in an ROI. But it is "calculated" from the lab worksheet.

2022-04-12 20:13 UTC, NicoleEO requested changes
utils.R comments

- Kind of odd that we now have two functions for read lab worksheet. It would be good in the future to importFrom GeomxTools. Can you start an issue documenting all v2 suggestsions?
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/utils.R#L31
- Add these as globals in the beginning of file or as function parameters with these set as defaults. 
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/utils.R#L82
- Why is this redefined?
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/utils.R#L98
- Use variable and basename() instead of real path name
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/utils.R#L105
- Add rox comments for these imports so we don't lose track in the future
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/utils.R#L112

2022-04-13 17:02 UTC, NicoleEO commented
removeSamples.R looks good, we should consider adding accessor functions in v2 to stop using direct slot access

2022-04-13 17:07 UTC, NicoleEO commented
readSpatialOverlay.R good

2022-04-13 18:16 UTC, NicoleEO commented
plottingBasics.R
- [ ] Ellipses not used anywhere in this function. https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/plottingBasics.R#L60
- [ ] If it is hard assigned and not a user input do you need the toupper and if stmt? Also, use the <- assignment operator for axis = X
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/plottingBasics.R#L242-L248
- [ ] Do you need this if? X is axis and the calc is exactly the same in if and else
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/plottingBasics.R#L275
- [ ] You have ellipses passed to both of these args. Do all args for one work for the other? Or is some parsing required? If you don't want to fix now suggest adding comment to do one or the other for the time being and add to v2 update.
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/plottingBasics.R#L281
- [ ] try to use intL for numbers throughout. You can fix later not urgent.
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/plottingBasics.R#L464

2022-04-13 18:26 UTC, NicoleEO commented
omeExtraction

- [ ] This could cause some issues depending on space in working directory. Might be nice to use a required param for directory to save to.
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/omeExtraction.R#L21
- [ ] Is this an imported function? If so, add importFrom.
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/omeExtraction.R#L30
- [ ] same here
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/omeExtraction.R#L46
- [ ] same about saveFile, add path param
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/omeExtraction.R#L83

2022-04-13 20:37 UTC, NicoleEO commented
- [ ] 1L
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/imageManipulation.R#L101
- [ ] is this right you potentially could calc maxheight - y twice if initial ymax > ymin? Done in L338 and again in L360 through 364
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/imageManipulation.R#L338
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/imageManipulation.R#L360-L364
- [ ] Is this an imported function? Add importFrom.
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/imageManipulation.R#L455
- [ ] Does this run the risk of being a different dimension than the list of AOIs in the object because you could filter out certain AOIs right with the logic statements? Or are all the samples kept in the overlay object and only coords used for plotting samples?
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/imageManipulation.R#L357-L365
- [ ] v2 enhancement, add list of samples ignored with warning
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/imageManipulation.R#L413
- [ ] is boundary imported, if so importFrom? I couldn't find where this was defined by search, but I feel like this is one of your funcs.
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/imageManipulation.R#L527
- [ ] Add importFrom
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/imageManipulation.R#L539

2022-04-13 22:18 UTC, NicoleEO commented
coordinateGeneration.R

- [ ] Can we put x before y, just to match the order you have throughout?
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/coordinateGeneration.R#L142
- [ ] 1L
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/coordinateGeneration.R#L167

2022-04-13 22:31 UTC, NicoleEO commented
addPlottingFactor.R
- [ ] Add importFrom
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/addPlottingFactor.R#L128

2022-04-13 22:36 UTC, NicoleEO commented
addImage is good

2022-04-13 22:46 UTC, NicoleEO commented
SpatialPosition looks good

2022-04-13 22:57 UTC, NicoleEO commented
-[ ] What is the signature these methods are matching on? Looks like these constructors don't really do anything. You can delete these and the generic probably and just keep the default constructor in prototype.
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/SpatialOverlay-class.R#L62-L93
- [ ] rox comments and exports of all the accessors. I found them manually entered. We should add to v2 to get this in rox comments instead. I have to do this in GxT as well at some point.
https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/blob/fd53a5690acd404c133be82a2499975a4e4d098d/R/SpatialOverlay-class.R#L154

2022-04-14 15:58 UTC, maddygriz commented
![image](https://user-images.githubusercontent.com/40255151/163428051-93cd1d1d-f00e-456c-ad46-cc9035f9b990.png)

2022-04-14 18:18 UTC, NicoleEO requested changes

2022-04-14 18:18 UTC, NicoleEO commented on R/addImage.R
> +    overlay@image  <- list(filePath = ometiff,
Looks like you accidentally added an extra space before <-

2022-04-14 18:18 UTC, NicoleEO commented on R/SpatialOverlay-class.R
> +
Add to export generics and methods these 3 functions

2022-04-14 18:18 UTC, NicoleEO commented on R/SpatialOverlay-class.R
> +
Add to export generics and methods these 3 functions

2022-04-14 18:19 UTC, NicoleEO commented
@maddygriz also see my mentions (@maddygriz) inside my previous comments for a couple of questions.

2022-04-17 01:49 UTC, maddygriz commented
no tests were written for adding the RBioFormat functions to the code base. The saved snaps used in vdiffr were made before changing the location of the code so if the generated images are the same between code bases, implementation should be the same.

2022-04-17 01:54 UTC, maddygriz commented
![image](https://user-images.githubusercontent.com/40255151/163696877-7fb9df4f-f7bf-43e2-b794-39154b417fba.png)
![image](https://user-images.githubusercontent.com/40255151/163696887-8be951b4-734f-47b2-9426-70d6ed61646c.png)

- one warning was taken care of 
![image](https://user-images.githubusercontent.com/40255151/163696909-b6cc8e2a-d6f7-4c9b-859a-c7de4e9ba58a.png)

- R CMD build errors seem to be based on latex, will look into them
![image](https://user-images.githubusercontent.com/40255151/163696939-e3b34c23-7f7e-4bd6-8168-2f10b540bb58.png)

2022-04-17 01:59 UTC, merged

2022-04-18 18:05 UTC, NicoleEO commented
Comments from here on are regarding [latest updates](https://github.com/Nanostring-Biostats/SpatialOmicsOverlay/compare/2ef56fb998d6083c1e969556cf73498049d02177...main#diff-9aadfeb2619230f5074f5536c75faeae15e69bef5c2706568727dfc96fb9e7a0L45).

2022-04-18 18:26 UTC, NicoleEO commented
@maddygriz If only very minor edits result from the below comments, let's wait until you get a reviewer assigned to fix these so hold the PR into main until then. In the meantime, let's get a dev branch setup.
- [ ] Line 45 and on in addImage, is difRes == 0 just not possible or you don't care about that case for running the lines that previously were in that case.
previously had: if(difRes != 0) 
- [ ] L523 in imageManipulation, I believe I saw this if statement a few times. Sometime with a ! and sometimes without. You may want to search and make sure coords is set right in your ifs throughout.
![image](https://user-images.githubusercontent.com/20404635/163854099-c8d80595-c357-4c68-be37-04d2655c3073.png)
- [ ] Line 416 in tests/testthat/test_plotting.R add another line at the bottom of script
- [ ] In RBioFormatsFunctions.R, I found a few instances of = instead of -> can you double-check to replace these?